"""Persistent Satchy rail and opt-in panels for the member workspace."""
# ruff: noqa: E501
from html import escape

from terrasatch.brand import SATCHY_ASSET_URL


def assistant_panel(organization: str, csrf_token: str) -> str:
    return f'''<aside class="satchy-rail" aria-label="Satchy assistant" data-organization="{escape(organization, quote=True)}" data-csrf="{escape(csrf_token, quote=True)}">
<div class="satchy-heading"><img src="{escape(SATCHY_ASSET_URL)}" alt="Satchy"><div><h2>Satchy</h2><p>What needs your attention?</p></div></div>
<button type="button" id="workspace-brief">Summarize my workspace</button>
<button type="button" id="choose-tools">Help me choose tools</button>
<div id="satchy-conversation" role="log" aria-live="polite"><p class="muted">Ask about your connected workspace or describe a workflow you want to simplify.</p></div>
<form id="satchy-form"><label for="satchy-prompt">Ask Satchy</label><textarea id="satchy-prompt" maxlength="4000" required placeholder="Describe what you need…"></textarea><button type="submit" class="primary">Ask Satchy</button></form><p id="satchy-status" role="status"></p>
<details class="panel-options"><summary>Workspace panels</summary><p>Choose what appears here. This does not change your subscription or connect a service.</p><form id="panel-preferences"><label><input type="checkbox" name="module" value="Map"> Map</label><label><input type="checkbox" name="module" value="Radio Log"> Activity</label><label><input type="checkbox" name="module" value="Observations"> Observations</label><label><input type="checkbox" name="module" value="Workflows"> Workflows</label><label><input type="checkbox" name="module" value="Satchy"> Satchy conversation</label><label for="work-context">Your work and priorities</label><textarea id="work-context" maxlength="1000" placeholder="For example: coordinate field crews and reduce handoffs."></textarea><button type="submit">Save my workspace</button></form><p id="preferences-status" role="status"></p></details>
<details class="panel-options"><summary>Monday.com</summary><p>Read-only board snapshot for authorized internal administrators.</p><button id="monday-refresh" type="button">Refresh Monday boards</button><button id="monday-summary" type="button">Summarize Monday boards</button><div id="monday-board-results" role="status">Not loaded. Refresh to check the connection.</div></details><div id="optional-panels"></div><p class="source-note">Board snapshots refresh on request. Calendar deadlines and automatic alerts are not connected.</p>
</aside>'''


def assistant_styles() -> str:
    return '''<style>.workspace-layout{grid-template-columns:170px minmax(0,1fr) 300px;gap:24px}.satchy-rail{border-left:1px solid var(--line);padding-left:22px;min-width:0}.satchy-heading{display:flex;gap:12px;align-items:center;margin-bottom:22px}.satchy-heading img{width:42px;height:42px;object-fit:contain}.satchy-heading h2{margin:0;font-size:24px}.satchy-heading p,.muted,.source-note{color:var(--muted);line-height:1.6}.satchy-heading p{margin:4px 0}.satchy-rail>button{width:100%;text-align:left;margin-bottom:10px;padding:14px}.satchy-rail textarea{width:100%;min-height:90px;resize:vertical;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:12px;border-radius:7px;font:13px/1.6 system-ui}.satchy-rail label{display:block;margin:10px 0;font-size:12px}.satchy-rail .primary{width:100%;background:#f59e0b;color:#101010;font-weight:700;margin-top:10px}.satchy-rail input[type=checkbox]{width:auto;margin-right:10px;accent-color:#f59e0b}.panel-options{border-top:1px solid var(--line);margin-top:22px;padding-top:20px}.panel-options summary{cursor:pointer;font-weight:700}.panel-options p,.source-note{font-size:11px}.source-note{margin-top:24px}.panel-options textarea{min-height:75px}#satchy-conversation{max-height:330px;overflow:auto;margin:16px 0;white-space:pre-wrap;overflow-wrap:anywhere}#satchy-conversation p{padding:10px 0;border-bottom:1px solid var(--line);font-size:13px;line-height:1.65}#satchy-conversation .question{color:#ffbd45}.optional-panel{border-top:1px solid var(--line);padding-top:14px;margin-top:18px}.optional-panel h3{font-size:14px}.optional-panel p{font-size:12px;color:var(--muted);overflow-wrap:anywhere}.optional-panel a{color:#ffbd45}.optional-panel iframe{width:100%;height:230px;border:0}.workspace-cards#services-list{display:block}.workspace-cards#services-list .workspace-card{border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;padding:18px 0}.workspace-cards#services-list .workspace-card h3{margin:8px 0}.workspace-cards#services-list .workspace-card p{margin:5px 0}main{max-width:1800px}.headline{margin-bottom:12px}.headline h1{font-size:22px}.headline p{font-size:12px}.section-heading h2{font-size:24px}#email .section-heading,#email>.section-intro{display:none}#workspace-inbox{margin-top:0;border:0;border-radius:0;height:calc(100vh - 180px)}@media(max-width:1200px){.workspace-layout{grid-template-columns:150px minmax(0,1fr)}.satchy-rail{grid-column:2;border-left:0;border-top:1px solid var(--line);padding:22px 0}.workspace-cards{grid-template-columns:1fr}}@media(max-width:700px){.workspace-layout{display:block}.satchy-rail{margin-top:24px}.headline h1{font-size:22px}#workspace-inbox{min-height:640px}}</style>'''


def assistant_script() -> str:
    return r'''<script>(()=>{
const rail=document.querySelector('.satchy-rail'),base='/api/v1/workspace/organizations/'+encodeURIComponent(rail.dataset.organization),log=document.getElementById('satchy-conversation'),status=document.getElementById('satchy-status'),prompt=document.getElementById('satchy-prompt');let state=null,loading=null,explicit={},busy=false;
function say(text,question=false){const p=document.createElement('p');p.textContent=text;p.className=question?'question':'';log.append(p);log.scrollTop=log.scrollHeight;while(log.children.length>40)log.firstElementChild.remove()}
async function api(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),body&&(path==='/chat'||path==='/monday/summary')?90000:15000);try{const r=await fetch(base+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','X-CSRF-Token':rail.dataset.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});if(r.status===401)throw Error('Your session expired. Sign in again.');if(!r.ok){let detail;try{detail=(await r.json()).detail}catch{}throw Error(typeof detail==='string'?detail:'This request could not be completed. Try again.')}return await r.json()}catch(e){if(e.name==='AbortError')throw Error('This took too long. Please try again.');throw e}finally{clearTimeout(timer)}}
function checked(){return [...document.querySelectorAll('[name=module]:checked')].map(c=>c.value)}
function section(title){const el=document.createElement('section');el.className='optional-panel';const h=document.createElement('h3');h.textContent=title;el.append(h);document.getElementById('optional-panels').append(el);return el}
function line(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p)}
function panels(){if(!state)return;document.getElementById('optional-panels').replaceChildren();const enabled=state.modules||[];document.getElementById('satchy-form').hidden=!enabled.includes('Satchy');log.hidden=!enabled.includes('Satchy');const records=state.records||[];if(enabled.includes('Map')){const box=section('Map');const points=records.flatMap(r=>r.interpretations||[]).filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude));line(box,points.length?'Select an authorized field location.':'No geolocated field records yet. Your map will appear when location data is available.');for(const p of points.slice(0,8)){const button=document.createElement('button');button.type='button';button.textContent=p.location||p.summary||'Field location';button.addEventListener('click',()=>{box.querySelector('iframe')?.remove();const f=document.createElement('iframe');f.title='OpenStreetMap field location';f.referrerPolicy='no-referrer';const x=p.longitude,y=p.latitude;f.src='https://www.openstreetmap.org/export/embed.html?bbox='+[x-.02,y-.02,x+.02,y+.02].join(',')+'&layer=mapnik&marker='+y+','+x;box.append(f)});box.append(button)}}if(enabled.includes('Radio Log')||enabled.includes('Observations')){const box=section('Recent activity');if(!records.length)line(box,'No field activity has been recorded.');records.slice(0,5).forEach(r=>line(box,(r.timestamp?new Date(r.timestamp).toLocaleString()+': ':'')+(r.original||r.source||'Field record')))}if(enabled.includes('Workflows')){const box=section('Workflows');const actions=state.actions||[];if(!actions.length)line(box,'No proposed workflows. Ask Satchy to help prepare a notification or report.');actions.slice(0,8).forEach(a=>{line(box,(a.status||'Unknown')+' · '+(a.reason||a.type));if(a.message)line(box,a.message)});line(box,'Proposals shown here do not send messages. Execution requires an authorized approval flow.')}}
async function load(){if(loading)return loading;loading=api('').then(data=>{state=data;explicit=data.satchy_preferences?.explicit||{};document.getElementById('work-context').value=explicit.work_context||'';document.querySelectorAll('[name=module]').forEach(c=>{c.checked=(data.modules||[]).includes(c.value)});panels();return data}).finally(()=>loading=null);return loading}
function brief(){const devices=state.integrations?.devices||[],actions=(state.actions||[]).filter(a=>['proposed','awaiting_approval'].includes(a.status));say('Workspace snapshot: '+devices.length+' registered devices, '+(state.records||[]).length+' recent field records, '+actions.length+' workflow proposals awaiting review. '+(state.sites?.length?'Context is available from '+state.sites.length+' sites.':'No enabled site is available for field-aware Satchy chat.')+' Monday.com tasks and calendar deadlines are not connected. Refresh this summary when you need an update.');}
document.getElementById('workspace-brief').addEventListener('click',async()=>{status.textContent='Loading workspace…';try{await load();log.hidden=false;brief();status.textContent='Updated just now.'}catch(e){status.textContent=e.message}});
document.getElementById('choose-tools').addEventListener('click',()=>{log.hidden=false;say('For field locations, enable Map. For recent field inputs, enable Activity. For proposed notifications and reports, enable Workflows. Describe your role and the process you want to shorten in Your work and priorities, then save. Tools & services shows what still needs configuration.');document.querySelector('.panel-options').open=true});
document.getElementById('panel-preferences').addEventListener('submit',async e=>{e.preventDefault();const out=document.getElementById('preferences-status'),button=e.submitter;button.disabled=true;out.textContent='Saving…';try{const result=await api('/preferences',{modules:checked(),satchy:{...explicit,work_context:document.getElementById('work-context').value}});explicit=result.satchy?.explicit||explicit;state={...(state||{}),modules:result.modules};panels();out.textContent='Saved to your account for this organization.'}catch(err){out.textContent=err.message}finally{button.disabled=false}});
document.getElementById('satchy-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const text=prompt.value.trim();if(!text)return;busy=true;e.submitter.disabled=true;status.textContent='Satchy is reviewing your request…';say(text,true);try{const result=await api('/chat',{message:text,objective:document.getElementById('work-context').value||undefined,request_id:crypto.randomUUID()});say(result.answer);prompt.value='';status.textContent=result.approval_required?'A proposal was prepared. Nothing has been sent.':'Response ready.'}catch(err){status.textContent=err.message}finally{busy=false;e.submitter.disabled=false}});
document.getElementById('monday-refresh').addEventListener('click',async e=>{const button=e.currentTarget,out=document.getElementById('monday-board-results');button.disabled=true;out.textContent='Loading…';try{const result=await api('/monday');out.replaceChildren();if(!result.connected){line(out,result.detail);return}for(const board of result.boards){line(out,board.name+(board.partial?' · first 100 items':'')+' · refreshed just now');for(const item of board.items.slice(0,20)){line(out,item.name+' — '+item.column_values.filter(c=>c.text).map(c=>c.text).join(' · '))}if(board.items.length>20)line(out,'Showing 20 of '+board.items.length+' loaded tasks.')}}catch(err){out.textContent=err.message}finally{button.disabled=false}});
document.getElementById('monday-summary').addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;status.textContent='Reviewing authorized boards…';try{const result=await api('/monday/summary',{});log.hidden=false;say(result.answer);status.textContent='Monday summary ready.'}catch(err){status.textContent=err.message}finally{button.disabled=false}});
load().catch(e=>{status.textContent=e.message});
})();</script>'''
